version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-houessou-com-attachments-service"
s3_prefix = "todo-houessou-com-attachments-service"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
